[project]
name = "ttyp"
version = "0.1.0"
description = "CLI typing test"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "prompt-toolkit>=3.0.51",
]
[build-system]
requires = ["uv_build>=0.7.12,<0.8.0"]
build-backend = "uv_build"

[project.scripts]
ttyp = "ttyp.main:main"
